version: "3.8"
services:
  flask_no_db:
    build:
      context: ./flask_no_db
    ports:
      - "5001:5000"
    networks:
      - app_network

  flask_with_db:
    build:
      context: ./flask_with_db
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/projectdb
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_no_db
      - flask_with_db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo_data:
