version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/projectdb


  mongodb:
    image: mongo:8.0.4
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
