replicaCount: 3

database:
  hostname: mongodb-service
  port: 27017

mongodb:
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
    size: 0.5Gi  
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

webdb:
  image:
    repository: leduc34/webdb
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 5000
  mongoUri: "mongodb://mychart-mongodb-service:27017"
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

webnodb:
  image:
    repository: leduc34/kubernetes
    tag: flask_no_db
    pullPolicy: IfNotPresent
  containerPort: 5000
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"
