apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: vmasseboeuf  # Replace with your namespace
spec:
  selector:
    app: webdb  # Match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Match your container port
  type: ClusterIP
