apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config
  namespace: {{ .Release.Namespace }}
data:
  DB_HOSTNAME: {{ .Values.mongodb.hostname | default "mongodb-service" | quote }}
  DB_PORT: {{ .Values.mongodb.port | default "27017" | quote }}
