---
# MongoDB Headless Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None 
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# webdb Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webdb-service
  labels:
    app: webdb
spec:
  type: ClusterIP 
  selector:
    app: webdb
  ports:
    - port: 80
      targetPort: {{ .Values.webdb.containerPort }}
---
# webnodb Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webnodb-service
  labels:
    app: webnodb
spec:
  type: ClusterIP 
  selector:
    app: webnodb
  ports:
    - port: 80
      targetPort: {{ .Values.webnodb.containerPort }}
