apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  serviceName: {{ .Release.Name }}-mongodb-service  # Uses headless service
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: "{{ .Values.mongodb.image.pullPolicy }}"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes:
          {{- toYaml .Values.mongodb.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
